"""make image legacy keys nullable

Revision ID: 159adbf3ab5e
Revises: da14f24fe562
Create Date: 2026-03-07 21:33:51.015972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159adbf3ab5e'
down_revision: Union[str, Sequence[str], None] = 'da14f24fe562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'original_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('images', 'thumb_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'thumb_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('images', 'original_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
